a = input('Enter the first number: ')
b = input('Enter the second number: ')
a = float(a)
b = float(b)
print('Addition: ', a + b)
print('Subtraction: ', a - b)
print('Multiplication: ', a * b)
print('Division: ', a / b)